#    This is a component of AXIS, a front-end for emc
#    Copyright 2004, 2005, 2006 Jeff Epler <jepler@unpythonic.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

errorlist = {
 0: 'No error',
 1: 'No error',
 2: 'No error',
 3: 'No error',
 4: 'A file is already open',
 5: 'All axes missing with g92',
 6: 'All axes missing with motion code',
 7: 'Arc radius too small to reach end point',
 8: 'Argument to acos out of range',
 9: 'Argument to asin out of range',
 10: 'Attempt to divide by zero',
 11: 'Attempt to raise negative to non integer power',
 12: 'Bad character used',
 13: 'Bad format unsigned integer',
 14: 'Bad number format',
 15: 'Bug bad g code modal group 0',
 16: 'Bug code not g0 or g1',
 17: 'Bug code not g17 g18 or g19',
 18: 'Bug code not g20 or g21',
 19: 'Bug code not g28 or g30',
 20: 'Bug code not g2 or g3',
 21: 'Bug code not g40 g41 or g42',
 22: 'Bug code not g43 or g49',
 23: 'Bug code not g4 g10 g28 g30 g53 or g92 series',
 24: 'Bug code not g61 g61 1 or g64',
 25: 'Bug code not g90 or g91',
 26: 'Bug code not g93 or g94',
 27: 'Bug code not g98 or g99',
 28: 'Bug code not in g92 series',
 29: 'Bug code not in range g54 to g593',
 30: 'Bug code not m0 m1 m2 m30 m60',
 31: 'Bug distance mode not g90 or g91',
 32: 'Bug function should not have been called',
 33: 'Bug in tool radius comp',
 34: 'Bug plane not xy yz or xz',
 35: 'Bug side not right or left',
 36: 'Bug unknown motion code',
 37: 'Bug unknown operation',
 38: 'Cannot change axis offsets with cutter radius comp',
 39: 'Cannot change units with cutter radius comp',
 40: 'Cannot create backup file',
 41: 'Cannot do g1 with zero feed rate',
 42: 'Cannot do zero repeats of cycle',
 43: 'Cannot make arc with zero feed rate',
 44: 'Cannot move rotary axes during probing',
 45: 'Cannot open backup file',
 46: 'Cannot open variable file',
 47: 'Cannot probe in inverse time feed mode',
 48: 'Cannot probe with cutter radius comp on',
 49: 'Cannot probe with zero feed rate',
 50: 'Cannot put a b in canned cycle',
 51: 'Cannot put a c in canned cycle',
 52: 'Cannot put an a in canned cycle',
 53: 'Cannot turn cutter radius comp on out of xy plane',
 54: 'Cannot turn cutter radius comp on when on',
 55: 'Cannot use a word',
 56: 'Cannot use axis values with g80',
 57: 'Cannot use axis values without a g code that uses them',
 58: 'Cannot use b word',
 59: 'Cannot use c word',
 60: 'Cannot use g28 or g30 with cutter radius comp',
 61: 'Cannot use g53 incremental',
 62: 'Cannot use g53 with cutter radius comp',
 63: 'Cannot use two g codes that both use axis values',
 64: 'Cannot use xz plane with cutter radius comp',
 65: 'Cannot use yz plane with cutter radius comp',
 66: 'Command too long',
 67: 'Concave corner with cutter radius comp',
 68: 'Coordinate system index parameter 5220 out of range',
 69: 'Current point same as end point of arc',
 70: 'Cutter gouging with cutter radius comp',
 71: 'D word with no g41 or g42',
 72: 'Dwell time missing with g4',
 73: 'Dwell time p word missing with g82',
 74: 'Dwell time p word missing with g86',
 75: 'Dwell time p word missing with g88',
 76: 'Dwell time p word missing with g89',
 77: 'Equal sign missing in parameter setting',
 78: 'F word missing with inverse time arc move',
 79: 'F word missing with inverse time g1 move',
 80: 'File ended with no percent sign',
 81: 'File ended with no percent sign or program end',
 82: 'File name too long',
 83: 'File not open',
 84: 'G code out of range',
 85: 'H word with no g43',
 86: 'I word given for arc in yz plane',
 87: 'I word missing with g87',
 88: 'I word with no g2 or g3 or g87 to use it',
 89: 'J word given for arc in xz plane',
 90: 'J word missing with g87',
 91: 'J word with no g2 or g3 or g87 to use it',
 92: 'K word given for arc in xy plane',
 93: 'K word missing with g87',
 94: 'K word with no g2 or g3 or g87 to use it',
 95: 'L word with no canned cycle or g10',
 96: 'Left bracket missing after slash with atan',
 97: 'Left bracket missing after unary operation name',
 98: 'Line number greater than 99999',
 99: 'Line with g10 does not have l2',
 100: 'M code greater than 199',
 101: 'Mixed radius ijk format for arc',
 102: 'Multiple a words on one line',
 103: 'Multiple b words on one line',
 104: 'Multiple c words on one line',
 105: 'Multiple d words on one line',
 106: 'Multiple f words on one line',
 107: 'Multiple h words on one line',
 108: 'Multiple i words on one line',
 109: 'Multiple j words on one line',
 110: 'Multiple k words on one line',
 111: 'Multiple l words on one line',
 112: 'Multiple p words on one line',
 113: 'Multiple q words on one line',
 114: 'Multiple r words on one line',
 115: 'Multiple s words on one line',
 116: 'Multiple t words on one line',
 117: 'Multiple x words on one line',
 118: 'Multiple y words on one line',
 119: 'Multiple z words on one line',
 120: 'Must use g0 or g1 with g53',
 121: 'Negative argument to sqrt',
 122: 'Negative d word tool radius index used',
 123: 'Negative f word used',
 124: 'Negative g code used',
 125: 'Negative h word tool length offset index used',
 126: 'Negative l word used',
 127: 'Negative m code used',
 128: 'Negative or zero q value used',
 129: 'Negative p word used',
 130: 'Negative spindle speed used',
 131: 'Negative tool id used',
 132: 'Nested comment found',
 133: 'No characters found in reading real value',
 134: 'No digits found where real number should be',
 135: 'Non integer value for integer',
 136: 'Null missing after newline',
 137: 'Offset index missing',
 138: 'P value not an integer with g10 l2',
 139: 'P value out of range with g10 l2',
 140: 'P word with no g4 g10 g82 g86 g88 g89',
 141: 'Parameter file out of order',
 142: 'Parameter number out of range',
 143: 'Q word missing with g83',
 144: 'Q word with no g83',
 145: 'Queue is not empty after probing',
 146: 'R clearance plane unspecified in cycle',
 147: 'R i j k words all missing for arc',
 148: 'R less than x in cycle in yz plane',
 149: 'R less than y in cycle in xz plane',
 150: 'R less than z in cycle in xy plane',
 151: 'R word with no g code that uses it',
 152: 'Radius to end of arc differs from radius to start',
 153: 'Radius too small to reach end point',
 154: 'Required parameter missing',
 155: 'Selected tool slot number too large',
 156: 'Slash missing after first atan argument',
 157: 'Spindle not turning clockwise in g84',
 158: 'Spindle not turning in g86',
 159: 'Spindle not turning in g87',
 160: 'Spindle not turning in g88',
 161: 'Sscanf failed',
 162: 'Start point too close to probe point',
 163: 'Too many m codes on line',
 164: 'Tool length offset index too big',
 165: 'Tool max too large',
 166: 'Tool radius index too big',
 167: 'Tool radius not less than arc radius with comp',
 168: 'Two g codes used from same modal group',
 169: 'Two m codes used from same modal group',
 170: 'Unable to open file',
 171: 'Unclosed comment found',
 172: 'Unclosed expression',
 173: 'Unknown g code used',
 174: 'Unknown m code used',
 175: 'Unknown operation',
 176: 'Unknown operation name starting with a',
 177: 'Unknown operation name starting with m',
 178: 'Unknown operation name starting with o',
 179: 'Unknown operation name starting with x',
 180: 'Unknown word starting with a',
 181: 'Unknown word starting with c',
 182: 'Unknown word starting with e',
 183: 'Unknown word starting with f',
 184: 'Unknown word starting with l',
 185: 'Unknown word starting with r',
 186: 'Unknown word starting with s',
 187: 'Unknown word starting with t',
 188: 'Unknown word where unary operation could be',
 189: 'X and y words missing for arc in xy plane',
 190: 'X and z words missing for arc in xz plane',
 191: 'X value unspecified in yz plane canned cycle',
 192: 'X y and z words all missing with g38 2',
 193: 'Y and z words missing for arc in yz plane',
 194: 'Y value unspecified in xz plane canned cycle',
 195: 'Z value unspecified in xy plane canned cycle',
 196: 'Zero or negative argument to ln',
 197: 'Zero radius arc',
 198: "K word missing with g33",
 199: "F word used with a g33",
 200: "G33 not supported",
 201: "Canned cycles not supported",
 202: "Unknown operation name starting with e",
 203: "Unknown operation name starting with n",
 204: "Unknown operation name starting with g",
 205: "Unknown operation name starting with l",
 206: "Too many subroutine parameters",
 207: "Too many subroutine levels",
 208: "Unknown control command in o word",
 209: "Too many oword labels",
 210: "Unknown oword number",
 211: "Nested subroutine definition",
 212: "Not in subroutine definition",
 213: "Return outside of subroutine",
 214: "File not open",
 215: "Unknown error"
}
 
RS274NGC_MIN_ERROR=3
RS274NGC_MAX_ERROR=215
