#    This is a component of AXIS, a front-end for emc
#    Copyright 2004, 2005, 2006 Jeff Epler <jepler@unpythonic.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

errorlist = {
    0: "RS274NGC_OK",
    1: "RS274NGC_EXIT",
    2: "RS274NGC_EXECUTE_FINISH",
    3: _("Unexpected end of file"),
    4: _("Internal error: A file is already open"),
    5: _("All axes missing with G92"),
    6: _("All axes missing with motion code"),
    7: _("Arc radius too small to reach endpoint"),
    8: _("Argument to ACOS out of range"),
    9: _("Argument to ASIN out of range"),
    10: _("Division by zero"),
    11: _("Attempt to raise negative number to non-integer power"),
    12: _("Bad character"),
    13: _("Non-digit found where integer expected"),
    14: _("Unexpected character found where +, -, . or digit expected"),
    15: _("Internal error: NCE_BUG_BAD_G_CODE_MODAL_GROUP_0"),
    16: _("Internal error: NCE_BUG_CODE_NOT_G0_OR_G1"),
    17: _("Internal error: NCE_BUG_CODE_NOT_G17_G18_OR_G19"),
    18: _("Internal error: NCE_BUG_CODE_NOT_G20_OR_G21"),
    19: _("Internal error: NCE_BUG_CODE_NOT_G28_OR_G30"),
    20: _("Internal error: NCE_BUG_CODE_NOT_G2_OR_G3"),
    21: _("Internal error: NCE_BUG_CODE_NOT_G40_G41_OR_G42"),
    22: _("Internal error: NCE_BUG_CODE_NOT_G43_OR_G49"),
    23: _("Internal error: NCE_BUG_CODE_NOT_G4_G10_G28_G30_G53_OR_G92_SERIES"),
    24: _("Internal error: NCE_BUG_CODE_NOT_G61_G61_1_OR_G64"),
    25: _("Internal error: NCE_BUG_CODE_NOT_G90_OR_G91"),
    26: _("Internal error: NCE_BUG_CODE_NOT_G93_OR_G94"),
    27: _("Internal error: NCE_BUG_CODE_NOT_G98_OR_G99"),
    28: _("Internal error: NCE_BUG_CODE_NOT_IN_G92_SERIES"),
    29: _("Internal error: NCE_BUG_CODE_NOT_IN_RANGE_G54_TO_G593"),
    30: _("Internal error: NCE_BUG_CODE_NOT_M0_M1_M2_M30_M60"),
    31: _("Internal error: NCE_BUG_DISTANCE_MODE_NOT_G90_OR_G91"),
    32: _("Internal error: NCE_BUG_FUNCTION_SHOULD_NOT_HAVE_BEEN_CALLED"),
    33: _("Internal error: NCE_BUG_IN_TOOL_RADIUS_COMP"),
    34: _("Internal error: NCE_BUG_PLANE_NOT_XY_YZ_OR_XZ"),
    35: _("Internal error: NCE_BUG_SIDE_NOT_RIGHT_OR_LEFT"),
    36: _("Internal error: NCE_BUG_UNKNOWN_MOTION_CODE"),
    37: _("Internal error: NCE_BUG_UNKNOWN_OPERATION"),
    38: _("Cannot change axis offsets with cutter radius compensation"),
    39: _("Cannot change units with cutter radius compensation"),
    40: _("Internal error: NCE_CANNOT_CREATE_BACKUP_FILE"),
    41: _("Cannot do G1 with zero feed rate"),
    42: _("Cannot do zero repeats of a cycle"),
    43: _("Cannot do arc with zero feed rate"),
    44: _("Cannot move rotary axes while probing"),
    45: _("Internal error: NCE_CANNOT_OPEN_BACKUP_FILE"),
    46: _("Internal error: NCE_CANNOT_OPEN_VARIABLE_FILE"),
    47: _("Cannot probe in inverse time feed mode"),
    48: _("Cannot probe with cutter radius compensation"),
    49: _("Cannot probe with zero feed rate"),
    50: _("Cannot put a B in a canned cycle"),
    51: _("Cannot put a C in a canned cycle"),
    52: _("Cannot put an A in a canned cycle"),
    53: _("Cannot turn cutter radius compensation on when out of XY plane (G17)"),
    54: _("Cannot turn cutter radius on when it is already on"),
    55: _("Cannot put an A word here"),
    56: _("Cannot use axis values with G80"),
    57: _("Cannot use an axis word without a G code that uses them"),
    58: _("Cannot put a B word here"),
    59: _("Cannot put a C word here"),
    60: _("Cannot use G28 or G30 with cutter radius compensation"),
    61: _("Cannot use G53 with incremental mode"),
    62: _("Cannot use G53 with cutter compensation"),
    63: _("Cannot use two G codes that use axis words"),
    64: _("Cannot use XZ plane with cutter radius compensation"),
    65: _("Cannot use YZ plane with cutter radius compensation"),
    66: _("Line too long"),
    67: _("Cannot have concave corners with cutter radius compensation"),
    68: _("Parameter 5220 (work coordinate system index) out of range"),
    69: _("Cannot start and end an R-format arc at the same place"),
    70: _("Arc would result in gouging with cutter radius compensation"),
    71: _("Cannot put a D word here (requires G41 or G42)"),
    72: _("Dwell time required with G4"),
    73: _("Dwell time required with G82"),
    74: _("Dwell time required with G86"),
    75: _("Dwell time required with G88"),
    76: _("Dwell time required with G89"),
    77: _("Equal sign missing in parameter setting"),
    78: _("F word required with inverse time arc move"),
    79: _("F word required with inverse time G1 move"),
    80: _("File ended with no percent sign"),
    81: _("File ended with no percent sign or program end"),
    82: _("Internal error: NCE_FILE_NAME_TOO_LONG"),
    83: _("Internal error: NCE_FILE_NOT_OPEN"),
    84: _("G code out of range"),
    85: _("Cannot put a H word here (requires G43)"),
    86: _("Cannot put an I word here (invalid plane)"),
    87: _("I word required with G87"),
    88: _("Cannot put an I word here (Only G2, G3, G87)"),
    89: _("Cannot put a J word here (invalid plane)"),
    90: _("I word reqired with G87"),
    91: _("Cannot put a J word here (Only G2, G3, G87)"),
    92: _("Cannot put a K word here (invalid plane)"),
    93: _("K word required with G87"),
    94: _("Cannot put a K word here (Only G2, G3, G87)"),
    95: _("L word requires canned cycle or G10"),
    96: _("Left bracket missing after slash with ATAN"),
    97: _("Left bracket missing after unary operation"),
    98: _("Line number greater than 99999"),
    99: _("NCE_LINE_WITH_G10_DOES_NOT_HAVE_L2"),
    100: _("M code out of range (Must not be greater than 199)"),
    101: _("R word and I/J/K words may not appear together for an arc"),
    102: _("Multiple A words on line"),
    103: _("Multiple B words on line"),
    104: _("Multiple C words on line"),
    105: _("Multiple D words on line"),
    106: _("Multiple F words on line"),
    107: _("Multiple H words on line"),
    108: _("Multiple I words on line"),
    109: _("Multiple J words on line"),
    110: _("Multiple K words on line"),
    111: _("Multiple L words on line"),
    112: _("Multiple P words on line"),
    113: _("Multiple Q words on line"),
    114: _("Multiple R words on line"),
    115: _("Multiple S words on line"),
    116: _("Multiple T words on line"),
    117: _("Multiple X words on line"),
    118: _("Multiple Y words on line"),
    119: _("Multiple Z words on line"),
    120: _("Must use G0 or G1 with G53"),
    121: _("Negative argument to SQRT"),
    122: _("Negative D word tool radius index used"),
    123: _("Negative F word used"),
    124: _("Negative G word used"),
    125: _("Negative H word tool length offset index used"),
    126: _("Negative L word used"),
    127: _("Negative M code used"),
    128: _("Negative or zero Q value used"),
    129: _("Negative P word used"),
    130: _("Negative spindle speed used"),
    131: _("Negative tool ID used"),
    132: _("Nested comment found"),
    133: _("No characters found when reading real value"),
    134: _("No digits found where real number should be"),
    135: _("Non-integer value found where integer required"),
    136: _("Internal error: NCE_NULL_MISSING_AFTER_NEWLINE"),
    137: _("Offset index missing"),
    138: _("P must be an integer with G10 L2"),
    139: _("P out of range with G10 L2"),
    140: _("P word with no G4, G10, G82, G86, G88, or G89"),
    141: _("Internal error: NCE_PARAMETER_FILE_OUT_OF_ORDER"),
    142: _("Parameter number out of range"),
    143: _("Q word missing with G83"),
    144: _("Q word without G83"),
    145: _("Internal error: NCE_QUEUE_IS_NOT_EMPTY_AFTER_PROBING"),
    146: _("R clearance plane unspecified in canned cycle"),
    147: _("Arc center unspecified (No R, I, J, or K words)"),
    148: _("R less than X in canned cycle in YZ plane"),
    149: _("R less than Y in canned cycle in XZ plane"),
    150: _("R less than Z in canned cycle in YX plane"),
    151: _("R word with G-code that does not use it"),
    152: _("Distance from center of arc to endpoints differs"),
    153: _("Arc radius too small to reach end point"),
    154: _("Required parameter missing"),
    155: _("Tool slot number too large"),
    156: _("Slash missing after first ATAN argument"),
    157: _("Spindle not turning clockwise in G84"),
    158: _("Spindle not turning in G86"),
    159: _("Spindle not turning in G87"),
    160: _("Spindle not turning in G88"),
    161: _("Non-number found where number expected (\"scanf()\" failed)"),
    162: _("Start pint too close to probe point"),
    163: _("Too many M codes on line"),
    164: _("Too length offset index too big"),
    165: _("Index in tool table file too large"),
    166: _("Tool radius index too big"),
    167: _("Tool radius must be less than arc radius with cutter compensation"),
    168: _("Two G codes from same modal group"),
    169: _("Two M codes from same modal group"),
    170: _("Unable to open file"),
    171: _("Unclosed comment"),
    172: _("Unclosed expresson"),
    173: _("Unknown G code"),
    174: _("Unknown M code"),
    175: _("Unknown operation"),
    176: _("Unknown operation name starting with A"),
    177: _("Unknown operation name starting with M"),
    178: _("Unknown operation name starting with O"),
    179: _("Unknown operation name starting with X"),
    180: _("Unknown word starting with A"),
    181: _("Unknown word starting with C"),
    182: _("Unknown word starting with E"),
    183: _("Unknown word starting with F"),
    184: _("Unknown word starting with L"),
    185: _("Unknown word starting with R"),
    186: _("Unknown word starting with S"),
    187: _("Unknown word starting with T"),
    188: _("Unknown word where unary operation could be"),
    189: _("X and Y words missing for arc in XY plane"),
    190: _("X and Z words missing for arc in XZ plane"),
    191: _("X value unspecified in YZ plane in a canned cycle"),
    192: _("X, Y, and Z words all missing with g38.2"),
    193: _("Y and Z words missing for arc in YZ plane"),
    194: _("Y value unspecified in XZ plane in a canned cycle"),
    195: _("Z value unspecified in XY plane in a canned cycle"),
    196: _("Zero or negative argument to LN"),
    197: _("Zero radius arc"),
    # 197: _("RS274NGC_MAX_ERROR")
}
RS274NGC_MIN_ERROR=3
RS274NGC_MAX_ERROR=197
